const PICKET_INIT = 0
const PICKET_ACTIVE = 1
const BOOM_INIT = 2
const BOOM_ACTIVE = 3
const BOOM_WARNING = 4
const BOOM_DANGEROUS_ZONE = 8
const FAKE_BOOM_WARNING = 5

const ROWS = 10
const COLUMNS = 10
const BOOMS = 10
const DEFAULT_REMAIN = 90

export {
  ROWS,
  COLUMNS,
  BOOMS,
  DEFAULT_REMAIN,
  PICKET_INIT,
  PICKET_ACTIVE,
  BOOM_INIT,
  BOOM_ACTIVE,
  BOOM_WARNING,
  BOOM_DANGEROUS_ZONE,
  FAKE_BOOM_WARNING,
}
